#!/usr/bin/env php
<?php

// https://wiki.corp.adobe.com/display/CENG/Checking+module+configuration

$path = getcwd();
echo $path;
$envPath = $path . '/app/etc/env.php';

if (!is_file($envPath)) {
    // @TODO ask for params
    $url="https://staging-vdt2zeq-5xc2bzxuexzme.us-3.magentosite.cloud/";
    $token = "2ygaf5zsYtialjeEE_tyNfvGsDTz6deeWeVuiSJQp9eREXM1rvtV5Egcx2uazoo2c__Tp-ffcbqWmprGY8L6jw";
} else {
    $config = include $envPath;
    $db = $config['db']['connection']['default'] ?? null;
    if (!$db) {
        die('Db config is empty');
    }

    $dsn = "mysql:host={$db['host']};dbname={$db['dbname']};charset=utf8mb4";
    $options = [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES   => false,
    ];
    try {
        $pdo = new PDO($dsn, $db['username'], $db['password'], $options);
    } catch (\PDOException $e) {
        throw new \PDOException($e->getMessage(), (int)$e->getCode());
    }

    $stmt = $pdo->query('SELECT * FROM core_config_data WHERE `path` = "analytics/general/token"');
    $tokenRow = $stmt->fetch();
    if ($tokenRow) {
        echo $tokenRow['value'];

        $token = $tokenRow['value'];
    }


    $stmt = $pdo->query('SELECT * FROM core_config_data WHERE `path` = "web/secure/base_url"');
    $baseUrlRow = $stmt->fetch();
    if ($baseUrlRow) {
        echo $baseUrlRow['value'];
        $url = $baseUrlRow['value'];
    }
}


$ch = curl_init();

curl_setopt($ch, CURLOPT_URL,"https://advancedreporting.rjmetrics.com/otp");
curl_setopt($ch, CURLOPT_POST, 1);

curl_setopt( $ch, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
// In real life you should use something like:
$payload = json_encode( [
    'access-token' => $token,
    'url' => $url
]);
 curl_setopt($ch, CURLOPT_POSTFIELDS,$payload);

// Receive server response ...
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$server_output = curl_exec($ch);

curl_close ($ch);

$response = json_decode($server_output, true);
if (isset($response['otp'])) {
    echo PHP_EOL;
    echo "https://advancedreporting.rjmetrics.com/report?otp={$response['otp']}";
    echo PHP_EOL;
} else {
    var_dump($server_output);
}